package csvtest;

public enum Field {
	RECOMMENDATION_ID, 
	RECOMMENDATION_SET_ID, 
	NUMBER_OF_RECOMMENDATIONS_IN_THE_RECOMMENDATION_SET, 
	RANK_IN_RECOMMENDATION_SET, 
	INPUT_DOCUMENT_MDL_ID, 
	INPUT_DOCUMENT_ORIGINAL_ID, 
	RECOMMENDED_DOCUMENT_MDL_ID, 
	TIME_REQUEST_RECEIVED, 
	TIME_RESPONSE_DELIVERED, 
	TIME_CLICKED, 
	ALGORITHM_ID, 
	RECOMMENDATION_CLASS, 
	ALGORITHM_CBF_DOCUMENT_FIELDS, 
	ALGORITHM_CBF_FEATURE_TYPE, 
	ALGORITHM_CBF_KEYPHRASE_COUNT, 
	TEXT_RELEVANCE_SCORE, 
	ALGORITHM_STEREOTYPE_MOST_POPULAR_DETAILS, 
	ALGORITHM_RE_RANKING_NUMBER_OF_CANDIDATES, 
	ALGORITHM_RE_RANKING_PERCENTAGE_OF_CANDIDATES_WITH_BIBLIOMETRICS, 
	ALGORITHM_COMBINATION_METHOD
}
